#!/bin/bash

jupyter labextension install --no-build @jupyterlab/celltags @jupyterlab/git @jupyterlab/github @jupyterlab/plotly-extension @jupyterlab/statusbar @jupyterlab/toc @mflevine/jupyterlab_html @rmotr/jupyterlab-solutions jupyterlab_bokeh jupyterlab-python-file @enlznep/runall-extension @krassowski/jupyterlab_go_to_definition @lckr/jupyterlab_variableinspector @parente/jupyterlab-quickopen @pyviz/jupyterlab_pyviz @jupyter-widgets/jupyterlab-manager bqplot jupyter-matplotlib jupyterlab-datawidgets jupyterlab-topbar-extension jupyterlab-system-monitor jupyterlab-drawio

jupyter lab build

jupyter serverextension enable --py jupyterlab_quickopen --user
jupyter serverextension enable --py jupyterlab_git
jupyter nbextension enable --py --sys-prefix pythreejs